Vagrant.configure("2") do |config|

  config.vm.provision :shell, :inline => "sh /vagrant/provision.sh;"

  # Defines the Vagrant box name, download URL, IP and hostname
  config.vm.define :vagrant do |vagrant|
    vagrant.vm.box = "precise64"
    vagrant.vm.box_url = "http://download.parallels.com/desktop/vagrant/precise64.box"

    vagrant.vm.network :private_network, ip: "192.168.66.6"
    vagrant.vm.network "forwarded_port", guest: 8983, host: 8985

    vagrant.vm.hostname = "vagrant.dcl"
  end

  #Update Guest tools
  config.vm.provider "parallels" do |v|
    v.update_guest_tools = true
  end
end
