'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ModelEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ModelEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Logs() As DbSet(Of Log)
    Public Overridable Property Servers() As DbSet(Of Server)
    Public Overridable Property Sites() As DbSet(Of Site)

End Class
