'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Log
    Public Property LogID As Long
    Public Property SiteID As Integer
    Public Property DateRequestEnd As Date
    Public Property ServerIP As String
    Public Property RequestMethod As String
    Public Property RequestURIBase As String
    Public Property RequestQueryString As String
    Public Property ServerPort As Short
    Public Property ClientUsername As String
    Public Property ClientIP As String
    Public Property ClientUserAgent As String
    Public Property HttpStatusCode As String
    Public Property HttpSubStatus As Short
    Public Property WindowsStatusCode As Short
    Public Property ProcessLength As Integer
    Public Property DateCreated As Date

    Public Overridable Property Site As Site

End Class
