'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Server
    Public Property ServerID As Integer
    Public Property ServerName As String

    Public Overridable Property Sites As ICollection(Of Site) = New HashSet(Of Site)

End Class
