'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Site
    Public Property SiteID As Integer
    Public Property ServerID As Integer
    Public Property SiteName As String

    Public Overridable Property Logs As ICollection(Of Log) = New HashSet(Of Log)
    Public Overridable Property Server As Server

End Class
